#! /bin/sh

# $Id$
# M.Boerger <re2c@somabo.de>

PREFIX="re2c"
VERSION="0.13.6"
TARDIR="`basename \`pwd\``"
RELEASE=${1:-1}

echo "Usage:"
echo "$0 <release>"
echo
echo "e.g.:"
echo "$0"
echo -n "Building RPM version $VERSION, release: $RELEASE "
sleep 1 ; echo -n . ; sleep 1 ; echo -n . ; sleep 1 ; echo -n .
echo

TAR=re2c-$VERSION.tar.gz
SPEC=re2c-${VERSION}.spec

RPMBASE=/usr/src/redhat
for i in /usr/src/redhat /usr/src/packages /usr/src/RPM; do
  if test -d $i; then
    RPMBASE=$i
    break
  fi
done

RPMDIR=${RPMBASE}/RPMS
SPECDIR=${RPMBASE}/SPECS
SRCDIR=${RPMBASE}/SOURCES

make dist
cp $TAR $SRCDIR

cat re2c.spec | sed -e "s/RPM_RELEASE/${RELEASE}/g" > ${SPEC}

echo "CP: (`pwd`) cp -a $SPEC $SPECDIR/${SPEC}"
cp -a $SPEC $SPECDIR/${SPEC}
#cp -a *.patch $SRCDIR
cd $SPECDIR
echo "RPM: rpm -ba ${SPEC}"
rpmbuild -ba ${SPEC}
